animal=input("Enter an animal:")
name=input("Enter a name:")
adjective1=input("Enter an adjective:")
color1=input("Enter a color:")
adjective2=input("Enter an adjective:")
noun1=input("Enter a noun:")
noun2=input("Enter a noun:")
noun3=input("Enter a noun:")
adjective3=input("Enter an adjective:")
color2=input("Enter a color:")
noun4=input("Enter a noun:")
name2=input("Enter a name:")
number=input("Enter a number:")
shape=input("Enter a shape:")
wound=input("Enter a wound type:")

print("I have a pet", animal, "named", name, ".")
print("He is", adjective1, ",", color1, "and", adjective2, ".")
print(name, "eats", noun1, ",", noun2, ", and", noun3, ".")
print("His favorite toy is a", adjective3, color2, noun4, ".")
print(name, "tries to eats my brother,", name2, "and has given him", number, shape, wound)